global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ingestor-service'
    static_configs:
      - targets: ['host.docker.internal:2112']

  - job_name: 'processor-service'
    static_configs:
      - targets: ['host.docker.internal:2113']
